preferred_syntax = :sass
http_path = '/'
css_dir = 'css'
sass_dir = 'css'
# images_dir = 'assets/images'
# javascripts_dir = 'assets/javascripts'
relative_assets = true
line_comments = false
# output_style = :compressed